// admin/src/features/dashboard/DashboardPage.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from "vue"
import { BarChart3, CreditCard, RefreshCw, TrendingUp, UserPlus, Users } from "lucide-vue-next"
import { BarChart, LineChart } from "echarts/charts"
import { GridComponent, TooltipComponent } from "echarts/components"
import { use } from "echarts/core"
import { CanvasRenderer } from "echarts/renderers"
import VChart from "vue-echarts"
import { NButton, NCard, NSpace } from "naive-ui"
import KpiCard from "@/components/common/KpiCard.vue"
import ErrorState from "@/components/common/ErrorState.vue"
import { metricsApi, type DailyRevenuePoint, type MetricsOverview, type PlanDistributionPoint } from "@/lib/api/metrics"
import { fmtCompact, fmtDate, fmtVnd } from "@/lib/format"

use([CanvasRenderer, LineChart, BarChart, GridComponent, TooltipComponent])

const overview = ref<MetricsOverview | null>(null)
const revenue = ref<DailyRevenuePoint[]>([])
const planDist = ref<PlanDistributionPoint[]>([])
const loading = ref(true)
const error = ref<string | null>(null)
let timer: ReturnType<typeof setInterval> | null = null

const revenueOption = computed(() => ({
  backgroundColor: "transparent",
  tooltip: { trigger: "axis", valueFormatter: (value: number) => fmtVnd(value) },
  grid: { left: 52, right: 16, top: 20, bottom: 32 },
  xAxis: { type: "category", data: revenue.value.map((p) => fmtDate(p.date).slice(0, 5)), axisLabel: { color: "#64748B" } },
  yAxis: { type: "value", axisLabel: { color: "#64748B", formatter: (value: number) => fmtCompact(value) }, splitLine: { lineStyle: { color: "#E2E8F0" } } },
  series: [{ type: "line", smooth: true, data: revenue.value.map((p) => p.revenue_vnd), showSymbol: false, lineStyle: { color: "#2563EB", width: 3 }, areaStyle: { color: "rgba(37, 99, 235, .12)" } }],
}))

const planOption = computed(() => ({
  backgroundColor: "transparent",
  tooltip: { trigger: "axis" },
  grid: { left: 92, right: 16, top: 20, bottom: 24 },
  xAxis: { type: "value", axisLabel: { color: "#64748B" }, splitLine: { lineStyle: { color: "#E2E8F0" } } },
  yAxis: { type: "category", data: planDist.value.map((p) => p.plan_name), axisLabel: { color: "#64748B" } },
  series: [{ type: "bar", data: planDist.value.map((p) => p.active_subscriptions), itemStyle: { color: "#0284C7", borderRadius: [0, 4, 4, 0] } }],
}))

async function load() {
  loading.value = true
  error.value = null
  try {
    const [ov, rv, pd] = await Promise.all([metricsApi.overview(), metricsApi.revenue(30), metricsApi.planDistribution()])
    overview.value = ov
    revenue.value = rv
    planDist.value = pd
  } catch (err) {
    error.value = err instanceof Error ? err.message : "Không thể tải dữ liệu"
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  void load()
  timer = setInterval(() => void load(), 60_000)
})
onUnmounted(() => { if (timer) clearInterval(timer) })
</script>

<template>
  <div class="page-stack">
    <div class="page-header">
      <div>
        <h1 class="page-title">Tổng quan</h1>
        <p class="page-subtitle">KPI người dùng, premium và giao dịch ảo</p>
      </div>
      <n-button secondary :loading="loading" @click="load"><template #icon><RefreshCw :size="16" /></template>Làm mới</n-button>
    </div>
    <ErrorState v-if="error" :message="error" @retry="load" />
    <div class="grid-kpis">
      <KpiCard label="Tổng người dùng" :value="fmtCompact(overview?.total_users ?? 0)" :sub-text="`Hôm nay: +${overview?.new_users_today ?? 0}`" :icon="Users" :loading="loading" />
      <KpiCard label="Người dùng mới" :value="overview?.new_users_today ?? 0" :sub-text="`7 ngày: ${overview?.new_users_last_7d ?? 0}`" :icon="UserPlus" :loading="loading" />
      <KpiCard label="Premium active" :value="overview?.active_paid_count ?? 0" :sub-text="`Trial: ${overview?.active_trial_count ?? 0}`" :icon="CreditCard" :loading="loading" />
      <KpiCard label="MRR" :value="fmtVnd(overview?.mrr_vnd ?? 0)" :sub-text="`30 ngày: ${fmtVnd(overview?.revenue_last_30d_vnd ?? 0)}`" :icon="TrendingUp" :loading="loading" />
    </div>
    <div class="charts">
      <n-card title="Doanh thu 30 ngày"><v-chart class="chart" :option="revenueOption" autoresize /></n-card>
      <n-card title="Phân bổ gói Premium"><v-chart class="chart" :option="planOption" autoresize /></n-card>
    </div>
    <n-space>
      <KpiCard label="VT active" :value="overview?.vt_active_accounts ?? 0" :icon="BarChart3" :loading="loading" />
      <KpiCard label="VT orders hôm nay" :value="overview?.vt_orders_today ?? 0" :loading="loading" />
    </n-space>
  </div>
</template>

<style scoped>
.charts {
  display: grid;
  gap: 16px;
  grid-template-columns: 7fr 3fr;
}
.chart {
  height: 300px;
}
@media (max-width: 1000px) {
  .charts { grid-template-columns: 1fr; }
}
</style>

// admin/src/features/dashboard/dashboard-page.tsx
import { useCallback, useEffect, useRef, useState } from "react"
import {
  Users,
  UserPlus,
  CreditCard,
  TrendingUp,
  RefreshCw,
} from "lucide-react"
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  BarChart,
  Bar,
  Cell,
} from "recharts"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Skeleton } from "@/components/ui/skeleton"
import { KpiCard } from "@/components/common/kpi-card"
import { ErrorState } from "@/components/common/error-state"
import {
  metricsApi,
  type MetricsOverview,
  type DailyRevenuePoint,
  type PlanDistributionPoint,
} from "@/lib/api/metrics"
import { fmtCompact, fmtVnd, fmtDate } from "@/lib/format"

const CHART_COLORS = [
  "#6366f1",
  "#8b5cf6",
  "#ec4899",
  "#f59e0b",
  "#10b981",
  "#3b82f6",
]

const AUTO_REFRESH_MS = 60_000

export default function DashboardPage() {
  const [overview, setOverview] = useState<MetricsOverview | null>(null)
  const [revenue, setRevenue] = useState<DailyRevenuePoint[]>([])
  const [planDist, setPlanDist] = useState<PlanDistributionPoint[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  const fetchAll = useCallback(async () => {
    setLoading(true)
    setError(null)
    try {
      const [ov, rv, pd] = await Promise.all([
        metricsApi.overview(),
        metricsApi.revenue(30),
        metricsApi.planDistribution(),
      ])
      setOverview(ov)
      setRevenue(rv)
      setPlanDist(pd)
    } catch (e) {
      setError(e instanceof Error ? e.message : "Không thể tải dữ liệu")
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    void fetchAll()
    timerRef.current = setInterval(() => { void fetchAll() }, AUTO_REFRESH_MS)
    return () => {
      if (timerRef.current) clearInterval(timerRef.current)
    }
  }, [fetchAll])

  if (error) {
    return (
      <div className="space-y-6">
        <Header loading={false} onRefresh={fetchAll} />
        <ErrorState message={error} onRetry={fetchAll} />
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <Header loading={loading} onRefresh={fetchAll} />

      {/* KPI Row */}
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <KpiCard
          label="Tổng người dùng"
          value={loading ? "—" : fmtCompact(overview?.total_users ?? 0)}
          subText={loading ? undefined : `Hôm nay: +${overview?.new_users_today ?? 0}`}
          icon={Users}
          loading={loading}
        />
        <KpiCard
          label="Người dùng mới hôm nay"
          value={loading ? "—" : String(overview?.new_users_today ?? 0)}
          subText={loading ? undefined : `7 ngày: ${overview?.new_users_last_7d ?? 0}`}
          icon={UserPlus}
          loading={loading}
        />
        <KpiCard
          label="Premium đang hoạt động"
          value={loading ? "—" : String(overview?.active_paid_count ?? 0)}
          subText={loading ? undefined : `Trial: ${overview?.active_trial_count ?? 0}`}
          icon={CreditCard}
          loading={loading}
        />
        <KpiCard
          label="MRR (ước tính)"
          value={loading ? "—" : fmtVnd(overview?.mrr_vnd ?? 0)}
          subText={
            loading
              ? undefined
              : `30 ngày: ${fmtVnd(overview?.revenue_last_30d_vnd ?? 0)}`
          }
          icon={TrendingUp}
          loading={loading}
        />
      </div>

      {/* Charts Row */}
      <div className="grid gap-4 lg:grid-cols-10">
        {/* Revenue Chart 70% */}
        <Card className="lg:col-span-7">
          <CardHeader>
            <CardTitle className="text-base">Doanh thu 30 ngày</CardTitle>
          </CardHeader>
          <CardContent>
            {loading ? (
              <Skeleton className="h-64 w-full" />
            ) : revenue.length === 0 ? (
              <div className="flex h-64 items-center justify-center text-sm text-muted-foreground">
                Chưa có dữ liệu doanh thu
              </div>
            ) : (
              <ResponsiveContainer width="100%" height={260}>
                <LineChart data={revenue} margin={{ top: 4, right: 4, bottom: 0, left: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" className="stroke-border" />
                  <XAxis
                    dataKey="date"
                    tickFormatter={(v: string) => {
                      try {
                        return fmtDate(v).slice(0, 5) // dd/MM
                      } catch {
                        return v
                      }
                    }}
                    tick={{ fontSize: 11 }}
                    tickLine={false}
                    axisLine={false}
                  />
                  <YAxis
                    tickFormatter={(v: number) => fmtCompact(v)}
                    tick={{ fontSize: 11 }}
                    tickLine={false}
                    axisLine={false}
                    width={60}
                  />
                  <Tooltip
                    formatter={(val: number) => [fmtVnd(val), "Doanh thu"]}
                    labelFormatter={(label: string) => {
                      try {
                        return fmtDate(label)
                      } catch {
                        return label
                      }
                    }}
                  />
                  <Line
                    type="monotone"
                    dataKey="revenue_vnd"
                    stroke="#6366f1"
                    strokeWidth={2}
                    dot={false}
                    activeDot={{ r: 4 }}
                  />
                </LineChart>
              </ResponsiveContainer>
            )}
          </CardContent>
        </Card>

        {/* Plan Distribution 30% */}
        <Card className="lg:col-span-3">
          <CardHeader>
            <CardTitle className="text-base">Phân bổ gói Premium</CardTitle>
          </CardHeader>
          <CardContent>
            {loading ? (
              <Skeleton className="h-64 w-full" />
            ) : planDist.length === 0 ? (
              <div className="flex h-64 items-center justify-center text-sm text-muted-foreground">
                Chưa có dữ liệu
              </div>
            ) : (
              <ResponsiveContainer width="100%" height={260}>
                <BarChart
                  data={planDist}
                  layout="vertical"
                  margin={{ top: 4, right: 8, bottom: 4, left: 0 }}
                >
                  <CartesianGrid strokeDasharray="3 3" className="stroke-border" horizontal={false} />
                  <XAxis
                    type="number"
                    tick={{ fontSize: 11 }}
                    tickLine={false}
                    axisLine={false}
                  />
                  <YAxis
                    type="category"
                    dataKey="plan_name"
                    width={80}
                    tick={{ fontSize: 11 }}
                    tickLine={false}
                    axisLine={false}
                  />
                  <Tooltip
                    formatter={(val: number) => [val, "Thuê bao"]}
                  />
                  <Bar dataKey="active_subscriptions" radius={[0, 4, 4, 0]}>
                    {planDist.map((_, idx) => (
                      <Cell key={idx} fill={CHART_COLORS[idx % CHART_COLORS.length]} />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  )
}

function Header({
  loading,
  onRefresh,
}: {
  loading: boolean
  onRefresh: () => void
}) {
  return (
    <div className="flex items-center justify-between">
      <div>
        <h1 className="text-2xl font-bold">Tổng quan</h1>
        <p className="text-sm text-muted-foreground">
          Cập nhật tự động mỗi 60 giây
        </p>
      </div>
      <Button variant="outline" size="sm" onClick={onRefresh} disabled={loading}>
        <RefreshCw className={`size-4 ${loading ? "animate-spin" : ""}`} />
        Làm mới
      </Button>
    </div>
  )
}
