// admin/src/features/users/UsersPage.vue
<script setup lang="ts">
import { h, onMounted, ref } from "vue"
import { RouterLink } from "vue-router"
import { Download, KeyRound, Mail, Search } from "lucide-vue-next"
import { NButton, NCard, NInput, NSelect, NSpace, type DataTableColumns } from "naive-ui"
import RemoteDataTable from "@/components/table/RemoteDataTable.vue"
import StatusTag from "@/components/common/StatusTag.vue"
import ErrorState from "@/components/common/ErrorState.vue"
import { feedback } from "@/lib/feedback"
import { fmtDateTime } from "@/lib/format"
import { useRemotePage } from "@/composables/useRemotePage"
import { usersApi, type AdminUserRow, type BulkOp } from "@/lib/api/users"

const searchText = ref("")
const role = ref<string | null>(null)
const status = ref<string | null>(null)
const checked = ref<Array<string | number>>([])
const bulkOp = ref<BulkOp | null>(null)
const bulkValue = ref<string | null>(null)
const exporting = ref(false)

const page = useRemotePage<AdminUserRow>((params) => usersApi.list({ page: Number(params.page), pageSize: Number(params.pageSize), sortBy: "created_at", sortDir: "desc", search: searchText.value || undefined, role: role.value || undefined, status: status.value || undefined }))

const roleOptions = [
  { label: "User", value: "user" },
  { label: "Premium", value: "premium" },
  { label: "Admin", value: "admin" },
]
const statusOptions = [
  { label: "Đang hoạt động", value: "active" },
  { label: "Không hoạt động", value: "inactive" },
  { label: "Bị đình chỉ", value: "suspended" },
]

const columns: DataTableColumns<AdminUserRow> = [
  { type: "selection" },
  { title: "Email", key: "email", minWidth: 240, render: (row) => h(RouterLink, { to: `/users/${row.id}` }, { default: () => row.email }) },
  { title: "Tên", key: "fullName", minWidth: 180, render: (row) => row.fullName ?? "-" },
  { title: "Vai trò", key: "role", width: 120, render: (row) => h(StatusTag, { status: row.role, label: row.role }) },
  { title: "Trạng thái", key: "status", width: 150, render: (row) => h(StatusTag, { status: row.status }) },
  { title: "Verified", key: "isEmailVerified", width: 110, render: (row) => h(StatusTag, { status: row.isEmailVerified }) },
  { title: "Đăng nhập", key: "lastLoginAt", width: 160, render: (row) => row.lastLoginAt ? fmtDateTime(row.lastLoginAt) : "-" },
  { title: "Tạo lúc", key: "createdAt", width: 160, render: (row) => fmtDateTime(row.createdAt) },
  { title: "Thao tác", key: "actions", width: 170, render: (row) => h(NSpace, { size: 4 }, { default: () => [h(NButton, { size: "small", secondary: true, onClick: () => resetPassword(row) }, { icon: () => h(KeyRound, { size: 14 }), default: () => "Reset" }), h(NButton, { size: "small", secondary: true, onClick: () => resend(row) }, { icon: () => h(Mail, { size: 14 }) })] }) },
]

function loadFirstPage() { void page.load({ page: 1 }) }

function resetPassword(user: AdminUserRow) {
  feedback.dialog?.warning({
    title: "Đặt lại mật khẩu?",
    content: `Tạo mật khẩu tạm thời cho ${user.email}.`,
    positiveText: "Đặt lại",
    negativeText: "Hủy",
    onPositiveClick: async () => {
      const res = await usersApi.resetPassword(user.id)
      feedback.dialog?.success({ title: "Mật khẩu tạm thời", content: res.temporary_password, positiveText: "Đã lưu" })
    },
  })
}

async function resend(user: AdminUserRow) {
  try {
    await usersApi.resendVerification(user.id)
    feedback.message?.success(`Đã gửi lại email xác thực cho ${user.email}`)
  } catch (error) {
    feedback.message?.error(error instanceof Error ? error.message : "Gửi thất bại")
  }
}

function applyBulk() {
  if (!bulkOp.value || checked.value.length === 0) return
  if (bulkOp.value !== "soft_delete" && !bulkValue.value) {
    feedback.message?.error("Vui lòng chọn giá trị áp dụng")
    return
  }
  feedback.dialog?.warning({
    title: "Áp dụng thao tác hàng loạt?",
    content: `Cập nhật ${checked.value.length} người dùng.`,
    positiveText: "Áp dụng",
    negativeText: "Hủy",
    onPositiveClick: async () => {
      const res = await usersApi.bulk({ user_ids: checked.value.map(String), op: bulkOp.value!, value: bulkOp.value === "soft_delete" ? null : bulkValue.value })
      feedback.message?.success(`Đã cập nhật ${res.affected} người dùng`)
      checked.value = []
      bulkOp.value = null
      bulkValue.value = null
      await page.load()
    },
  })
}

async function exportCsv() {
  exporting.value = true
  try {
    const filters: Record<string, string> = {}
    if (searchText.value) filters.search = searchText.value
    if (role.value) filters.role = role.value
    if (status.value) filters.status = status.value
    await usersApi.exportCsv(filters)
    feedback.message?.success("Đã xuất CSV thành công")
  } catch (error) {
    feedback.message?.error(error instanceof Error ? error.message : "Export thất bại")
  } finally {
    exporting.value = false
  }
}

onMounted(() => void page.load())
</script>

<template>
  <div class="page-stack">
    <div class="page-header"><div><h1 class="page-title">Người dùng</h1><p class="page-subtitle">{{ page.total.value }} người dùng</p></div><n-button secondary :loading="exporting" @click="exportCsv"><template #icon><Download :size="16" /></template>Export CSV</n-button></div>
    <n-card>
      <n-space align="center" wrap>
        <n-input v-model:value="searchText" clearable placeholder="Tìm email, tên..." style="width: 260px" @keyup.enter="loadFirstPage"><template #prefix><Search :size="16" /></template></n-input>
        <n-select v-model:value="role" clearable :options="roleOptions" placeholder="Vai trò" style="width: 160px" @update:value="loadFirstPage" />
        <n-select v-model:value="status" clearable :options="statusOptions" placeholder="Trạng thái" style="width: 180px" @update:value="loadFirstPage" />
        <n-button type="primary" @click="loadFirstPage">Lọc</n-button>
      </n-space>
    </n-card>
    <n-card v-if="checked.length" size="small">
      <n-space align="center" wrap>
        <span>Đã chọn {{ checked.length }} người dùng</span>
        <n-select v-model:value="bulkOp" placeholder="Thao tác" :options="[{ label: 'Đặt vai trò', value: 'set_role' }, { label: 'Đặt trạng thái', value: 'set_status' }, { label: 'Xóa mềm', value: 'soft_delete' }]" style="width: 180px" @update:value="bulkValue = null" />
        <n-select v-if="bulkOp === 'set_role'" v-model:value="bulkValue" :options="roleOptions" placeholder="Vai trò" style="width: 160px" />
        <n-select v-if="bulkOp === 'set_status'" v-model:value="bulkValue" :options="statusOptions" placeholder="Trạng thái" style="width: 180px" />
        <n-button type="primary" @click="applyBulk">Áp dụng</n-button>
        <n-button secondary @click="checked = []">Bỏ chọn</n-button>
      </n-space>
    </n-card>
    <ErrorState v-if="page.error.value" :message="page.error.value" @retry="page.load" />
    <RemoteDataTable :columns="columns" :rows="page.rows.value" :loading="page.loading.value" :page="page.params.page" :page-size="page.params.pageSize" :item-count="page.total.value" :row-key="(row) => row.id" :checked-row-keys="checked" @update-checked-row-keys="checked = $event" @page-change="page.setPage" @page-size-change="page.setPageSize" />
  </div>
</template>

// admin-bak/src/features/users/users-page.tsx
import { useState } from "react"
import type { DateRange } from "react-day-picker"
import type { RowSelectionState } from "@tanstack/react-table"
import { toast } from "sonner"
import { DataTable } from "@/components/data-table/data-table"
import { DataTablePagination } from "@/components/data-table/data-table-pagination"
import { DataTableBulkActions } from "@/components/data-table/data-table-bulk-actions"
import { ConfirmDialog } from "@/components/common/confirm-dialog"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { CopyButton } from "@/components/common/copy-button"
import { usePaginatedQuery } from "@/hooks/use-paginated-query"
import { usersApi, type AdminUserRow, type BulkOp } from "@/lib/api/users"
import { buildColumns } from "./columns"
import { UsersFilters } from "./filters"

export default function UsersPage() {
  // ── Selection ──────────────────────────────────────────────────────────
  const [rowSelection, setRowSelection] = useState<RowSelectionState>({})

  // ── Filters ────────────────────────────────────────────────────────────
  const [search, setSearch] = useState("")
  const [roles, setRoles] = useState<string[]>([])
  const [statuses, setStatuses] = useState<string[]>([])
  const [loginRange, setLoginRange] = useState<DateRange | undefined>()

  // ── Bulk state ─────────────────────────────────────────────────────────
  const [bulkOp, setBulkOp] = useState<BulkOp | "">("")
  const [bulkValue, setBulkValue] = useState("")
  const [confirmBulk, setConfirmBulk] = useState(false)
  const [bulkLoading, setBulkLoading] = useState(false)

  // ── Reset password dialog ──────────────────────────────────────────────
  const [resetTarget, setResetTarget] = useState<AdminUserRow | null>(null)
  const [tempPassword, setTempPassword] = useState<string | null>(null)
  const [resetLoading, setResetLoading] = useState(false)

  // ── CSV export ─────────────────────────────────────────────────────────
  const [exporting, setExporting] = useState(false)

  // ── Paginated query ────────────────────────────────────────────────────
  const { data, isLoading, params, setParams, refetch } = usePaginatedQuery<AdminUserRow>({
    queryFn: (p) =>
      usersApi.list({
        page: p.page,
        pageSize: p.pageSize,
        sortBy: p.sortBy,
        sortDir: p.sortDir,
        role: roles.length === 1 ? roles[0] : undefined,
        status: statuses.length === 1 ? statuses[0] : undefined,
        search: search || undefined,
      }),
    defaults: { page: 1, pageSize: 20, sortBy: "created_at", sortDir: "desc" },
  })

  // Re-fetch when filters change
  const handleSearchChange = (v: string) => {
    setSearch(v)
    setParams({ search: v, page: 1 })
  }

  const handleRolesChange = (v: string[]) => {
    setRoles(v)
    setParams({ role: v.length === 1 ? v[0] : "", page: 1 })
  }

  const handleStatusesChange = (v: string[]) => {
    setStatuses(v)
    setParams({ status: v.length === 1 ? v[0] : "", page: 1 })
  }

  // Selected rows
  const selectedIds = Object.keys(rowSelection).filter((k) => rowSelection[k])
  const selectedCount = selectedIds.length

  // ── Bulk confirm ───────────────────────────────────────────────────────
  const handleBulkConfirm = async () => {
    if (!bulkOp) return
    setBulkLoading(true)
    try {
      const body = {
        user_ids: selectedIds,
        op: bulkOp,
        value: bulkOp !== "soft_delete" ? bulkValue : null,
      }
      const res = await usersApi.bulk(body)
      toast.success(`Đã cập nhật ${res.affected} người dùng`)
      setRowSelection({})
      setBulkOp("")
      setBulkValue("")
      refetch()
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Thao tác thất bại")
    } finally {
      setBulkLoading(false)
    }
  }

  // ── Reset password ─────────────────────────────────────────────────────
  const handleResetPassword = async (user: AdminUserRow) => {
    setResetTarget(user)
    setTempPassword(null)
    setResetLoading(true)
    try {
      const res = await usersApi.resetPassword(user.id)
      setTempPassword(res.temporary_password)
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Không thể đặt lại mật khẩu")
      setResetTarget(null)
    } finally {
      setResetLoading(false)
    }
  }

  // ── Resend verification ────────────────────────────────────────────────
  const handleResendVerification = async (user: AdminUserRow) => {
    try {
      await usersApi.resendVerification(user.id)
      toast.success(`Đã gửi lại email xác thực cho ${user.email}`)
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Gửi thất bại")
    }
  }

  // ── Export CSV ─────────────────────────────────────────────────────────
  const handleExportCsv = async () => {
    setExporting(true)
    try {
      const filters: Record<string, string> = {}
      if (search) filters.search = search
      if (roles.length === 1) filters.role = roles[0]
      if (statuses.length === 1) filters.status = statuses[0]
      if (loginRange?.from)
        filters.last_login_from = loginRange.from.toISOString()
      if (loginRange?.to)
        filters.last_login_to = loginRange.to.toISOString()
      await usersApi.exportCsv(filters)
      toast.success("Đã xuất CSV thành công")
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Export thất bại")
    } finally {
      setExporting(false)
    }
  }

  const columns = buildColumns({
    onResetPassword: (u) => { void handleResetPassword(u) },
    onResendVerification: (u) => { void handleResendVerification(u) },
  })

  const pagination = {
    pageIndex: (params.page ?? 1) - 1,
    pageSize: params.pageSize ?? 20,
  }

  return (
    <div className="space-y-4">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold">Người dùng</h1>
        <p className="text-sm text-muted-foreground">
          {data ? `${data.total} người dùng` : ""}
        </p>
      </div>

      {/* Filters */}
      <UsersFilters
        search={search}
        onSearchChange={handleSearchChange}
        roles={roles}
        onRolesChange={handleRolesChange}
        statuses={statuses}
        onStatusesChange={handleStatusesChange}
        loginRange={loginRange}
        onLoginRangeChange={setLoginRange}
        onExportCsv={() => { void handleExportCsv() }}
        exporting={exporting}
      />

      {/* Bulk toolbar */}
      <DataTableBulkActions
        selectedCount={selectedCount}
        onClearSelection={() => setRowSelection({})}
      >
        <Select
          value={bulkOp}
          onValueChange={(v) => {
            setBulkOp((v ?? "") as BulkOp | "")
            setBulkValue("")
          }}
        >
          <SelectTrigger className="h-7 w-36 text-xs">
            <SelectValue placeholder="Chọn thao tác" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="set_role">Đặt vai trò</SelectItem>
            <SelectItem value="set_status">Đặt trạng thái</SelectItem>
            <SelectItem value="soft_delete">Xoá mềm</SelectItem>
          </SelectContent>
        </Select>

        {bulkOp === "set_role" && (
          <Select value={bulkValue} onValueChange={(v) => setBulkValue(v ?? "")}>
            <SelectTrigger className="h-7 w-28 text-xs">
              <SelectValue placeholder="Vai trò" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="user">User</SelectItem>
              <SelectItem value="premium">Premium</SelectItem>
              <SelectItem value="admin">Admin</SelectItem>
            </SelectContent>
          </Select>
        )}

        {bulkOp === "set_status" && (
          <Select value={bulkValue} onValueChange={(v) => setBulkValue(v ?? "")}>
            <SelectTrigger className="h-7 w-32 text-xs">
              <SelectValue placeholder="Trạng thái" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="active">Đang hoạt động</SelectItem>
              <SelectItem value="inactive">Không hoạt động</SelectItem>
              <SelectItem value="suspended">Bị đình chỉ</SelectItem>
            </SelectContent>
          </Select>
        )}

        <Button
          size="sm"
          className="h-7 text-xs"
          disabled={
            !bulkOp ||
            (bulkOp !== "soft_delete" && !bulkValue) ||
            bulkLoading
          }
          onClick={() => setConfirmBulk(true)}
        >
          Áp dụng
        </Button>
      </DataTableBulkActions>

      {/* Table */}
      <DataTable
        columns={columns}
        data={data?.items ?? []}
        pageCount={data?.totalPages ?? 1}
        pagination={pagination}
        onPaginationChange={(updater) => {
          const next =
            typeof updater === "function" ? updater(pagination) : updater
          setParams({ page: next.pageIndex + 1, pageSize: next.pageSize })
        }}
        rowSelection={rowSelection}
        onRowSelectionChange={setRowSelection}
        loading={isLoading}
        emptyMessage="Không tìm thấy người dùng"
      />

      {/* Pagination */}
      <DataTablePagination
        pagination={pagination}
        pageCount={data?.totalPages ?? 1}
        onPaginationChange={(updater) => {
          const next =
            typeof updater === "function" ? updater(pagination) : updater
          setParams({ page: next.pageIndex + 1, pageSize: next.pageSize })
        }}
        total={data?.total}
      />

      {/* Bulk confirm dialog */}
      <ConfirmDialog
        open={confirmBulk}
        onOpenChange={setConfirmBulk}
        title="Xác nhận thao tác hàng loạt"
        description={`Áp dụng "${bulkOp}" cho ${selectedCount} người dùng đã chọn?`}
        destructive={bulkOp === "soft_delete"}
        confirmLabel={bulkLoading ? "Đang xử lý..." : "Xác nhận"}
        onConfirm={handleBulkConfirm}
      />

      {/* Reset password dialog */}
      <Dialog
        open={!!resetTarget}
        onOpenChange={(open) => {
          if (!open) {
            setResetTarget(null)
            setTempPassword(null)
          }
        }}
      >
        <DialogContent className="max-w-sm">
          <DialogHeader>
            <DialogTitle>Đặt lại mật khẩu</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            {resetLoading ? (
              <p className="text-sm text-muted-foreground">Đang tạo mật khẩu...</p>
            ) : tempPassword ? (
              <>
                <p className="text-sm text-muted-foreground">
                  Mật khẩu tạm thời cho{" "}
                  <strong>{resetTarget?.email}</strong>:
                </p>
                <div className="flex items-center gap-2 rounded-md border bg-muted/50 px-3 py-2">
                  <code className="flex-1 text-sm font-mono break-all">
                    {tempPassword}
                  </code>
                  <CopyButton text={tempPassword} />
                </div>
                <p className="text-xs text-amber-600">
                  Hãy chia sẻ mật khẩu này một cách an toàn. Mật khẩu sẽ không được gửi qua email.
                </p>
              </>
            ) : null}
          </div>
        </DialogContent>
      </Dialog>
    </div>
  )
}
