// admin/src/features/auth/LoginPage.vue
<script setup lang="ts">
import { ref } from "vue"
import { useRoute, useRouter } from "vue-router"
import { Eye, EyeOff, ShieldCheck } from "lucide-vue-next"
import { NButton, NCard, NForm, NFormItem, NIcon, NInput, NSpace, NText } from "naive-ui"
import { feedback } from "@/lib/feedback"
import { useAuthStore } from "@/stores/auth"

const route = useRoute()
const router = useRouter()
const auth = useAuthStore()
const email = ref("")
const password = ref("")
const showPassword = ref(false)
const submitting = ref(false)

async function submit() {
  if (!email.value || !password.value) {
    feedback.message?.error("Vui lòng nhập đầy đủ email và mật khẩu")
    return
  }
  submitting.value = true
  try {
    await auth.login({ email: email.value, password: password.value })
    await router.replace(typeof route.query.redirect === "string" ? route.query.redirect : "/")
  } catch (error) {
    feedback.message?.error(error instanceof Error ? error.message : "Đăng nhập thất bại")
  } finally {
    submitting.value = false
  }
}
</script>

<template>
  <main class="login-page">
    <n-card class="login-card" :bordered="true">
      <n-space vertical align="center" size="small" class="login-head">
        <div class="login-icon"><ShieldCheck :size="26" /></div>
        <h1>IQX Admin</h1>
        <n-text depth="3">Đăng nhập để truy cập trang quản trị</n-text>
      </n-space>
      <n-form @submit.prevent="submit">
        <n-form-item label="Email">
          <n-input v-model:value="email" placeholder="admin@example.com" autocomplete="email" :input-props="{ type: 'email' }" :disabled="submitting" />
        </n-form-item>
        <n-form-item label="Mật khẩu">
          <n-input v-model:value="password" :type="showPassword ? 'text' : 'password'" placeholder="••••••••" autocomplete="current-password" :disabled="submitting">
            <template #suffix>
              <n-button quaternary circle size="small" @click="showPassword = !showPassword">
                <template #icon><n-icon :component="showPassword ? EyeOff : Eye" /></template>
              </n-button>
            </template>
          </n-input>
        </n-form-item>
        <n-button type="primary" attr-type="submit" block :loading="submitting">Đăng nhập</n-button>
      </n-form>
    </n-card>
  </main>
</template>

<style scoped>
.login-page {
  align-items: center;
  background: #061224;
  display: flex;
  min-height: 100vh;
  justify-content: center;
  padding: 24px;
}
.login-card {
  max-width: 400px;
  width: 100%;
}
.login-head {
  margin-bottom: 22px;
  text-align: center;
}
.login-head h1 {
  font-size: 24px;
  margin: 0;
}
.login-icon {
  align-items: center;
  background: #102d55;
  border-radius: 10px;
  color: #5a9ef4;
  display: flex;
  height: 52px;
  justify-content: center;
  width: 52px;
}
</style>

// admin-bak/src/features/auth/login-page.tsx
import { useState } from "react"
import { useNavigate } from "react-router"
import { toast } from "sonner"
import { Eye, EyeOff, ShieldCheck } from "lucide-react"
import { useAuth } from "@/contexts/auth-context"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"

export function LoginPage() {
  const { login } = useAuth()
  const navigate = useNavigate()
  const [email, setEmail] = useState("")
  const [password, setPassword] = useState("")
  const [showPassword, setShowPassword] = useState(false)
  const [isSubmitting, setIsSubmitting] = useState(false)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!email || !password) {
      toast.error("Vui lòng nhập đầy đủ email và mật khẩu")
      return
    }
    setIsSubmitting(true)
    try {
      await login({ email, password })
      void navigate("/", { replace: true })
    } catch (err) {
      const message =
        err instanceof Error ? err.message : "Đăng nhập thất bại. Vui lòng thử lại."
      toast.error(message)
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <div className="flex min-h-screen items-center justify-center bg-background px-4">
      <Card className="w-full max-w-sm">
        <CardHeader className="text-center">
          <div className="mx-auto mb-2 flex size-12 items-center justify-center rounded-full bg-primary/10">
            <ShieldCheck className="size-6 text-primary" />
          </div>
          <CardTitle className="text-2xl">IQX Admin</CardTitle>
          <CardDescription>Đăng nhập để truy cập trang quản trị</CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={(e) => { void handleSubmit(e) }} className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input
                id="email"
                type="email"
                placeholder="admin@example.com"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                autoComplete="email"
                disabled={isSubmitting}
                required
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="password">Mật khẩu</Label>
              <div className="relative">
                <Input
                  id="password"
                  type={showPassword ? "text" : "password"}
                  placeholder="••••••••"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  autoComplete="current-password"
                  disabled={isSubmitting}
                  required
                  className="pr-10"
                />
                <button
                  type="button"
                  onClick={() => setShowPassword((v) => !v)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
                  tabIndex={-1}
                  aria-label={showPassword ? "Ẩn mật khẩu" : "Hiện mật khẩu"}
                >
                  {showPassword ? <EyeOff className="size-4" /> : <Eye className="size-4" />}
                </button>
              </div>
            </div>
            <Button type="submit" className="w-full" disabled={isSubmitting}>
              {isSubmitting ? "Đang đăng nhập..." : "Đăng nhập"}
            </Button>
          </form>
        </CardContent>
      </Card>
    </div>
  )
}
