// frontend/src/pages/admin/core/users-page.tsx
import { useState, type FormEvent } from "react"
import { Link } from "react-router"
import { Copy, Download, KeyRound, Mail, RotateCw, Search, UserCog } from "lucide-react"
import { toast } from "sonner"

import { WorkspacePage } from "@/components/layout/workspace-page"
import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogContent,
} from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { errorMessage } from "@/lib/api"
import { formatDateTime } from "@/lib/format"

import {
  ADMIN_ROLES,
  ADMIN_STATUSES,
  ASSIGNABLE_STATUSES,
  type AdminUserRow,
  type BulkOp,
  type ResetPasswordResult,
  type UserSortField,
} from "./api"
import { AdminDataTable, type AdminColumn, type AdminSort } from "./components/admin-data-table"
import { useConfirmDialog } from "./components/use-confirm-dialog"
import { StatusBadge } from "./components/status-badge"
import {
  useAdminUsers,
  useBulkUpdateUsers,
  useExportUsersCsv,
  useResetUserPassword,
  useResendUserVerification,
} from "./hooks"
import { labelForRole, labelForStatus } from "./labels"

const ALL = "all"

const ROLE_LABELS_BY_VALUE: Record<string, string> = Object.fromEntries(
  ADMIN_ROLES.map((role) => [role, labelForRole(role)]),
)

const BULK_OP_LABELS: Record<BulkOp, string> = {
  set_role: "Đặt vai trò",
  set_status: "Đặt trạng thái",
  soft_delete: "Xóa mềm",
}

type Filters = { search: string; role: string; status: string }

export function UsersPage() {
  const [searchInput, setSearchInput] = useState("")
  const [filters, setFilters] = useState<Filters>({ search: "", role: ALL, status: ALL })
  const [page, setPage] = useState(1)
  const [pageSize, setPageSize] = useState(20)
  const [sort, setSort] = useState<AdminSort>({ field: "created_at", dir: "desc" })
  const [selected, setSelected] = useState<string[]>([])
  const [bulkOp, setBulkOp] = useState<BulkOp | "">("")
  const [bulkValue, setBulkValue] = useState("")
  const [temporaryPassword, setTemporaryPassword] = useState<ResetPasswordResult | null>(null)

  const users = useAdminUsers({
    page,
    pageSize,
    sortBy: sort.field as UserSortField,
    sortDir: sort.dir,
    role: filters.role === ALL ? undefined : filters.role,
    status: filters.status === ALL ? undefined : filters.status,
    search: filters.search || undefined,
  })
  const bulk = useBulkUpdateUsers()
  const resetPassword = useResetUserPassword()
  const resendVerification = useResendUserVerification()
  const exportCsv = useExportUsersCsv()
  const confirm = useConfirmDialog()

  const rows = users.data?.items ?? []
  const emailById = new Map(rows.map((row) => [row.id, row.email]))

  function applyFilters(next: Partial<Filters>) {
    setFilters((previous) => ({ ...previous, ...next }))
    setPage(1)
    setSelected([])
  }

  function submitSearch(event: FormEvent) {
    event.preventDefault()
    applyFilters({ search: searchInput.trim() })
  }

  function changeSort(field: string) {
    setSort((previous) =>
      previous.field === field ? { field, dir: previous.dir === "asc" ? "desc" : "asc" } : { field, dir: "asc" },
    )
    setPage(1)
  }

  function askResetPassword(user: AdminUserRow) {
    confirm.ask({
      title: "Đặt lại mật khẩu?",
      description: `Mật khẩu hiện tại của ${user.email} sẽ bị thay thế bằng một mật khẩu tạm thời do hệ thống sinh ra.`,
      confirmLabel: "Đặt lại",
      body: (
        <p className="text-muted-foreground">
          Hệ thống cũng gửi email đặt lại mật khẩu tới người dùng; mật khẩu tạm thời trả về ngay sau đó để
          chia sẻ dự phòng nếu email không tới.
        </p>
      ),
      run: async () => {
        try {
          const result = await resetPassword.mutateAsync(user.id)
          setTemporaryPassword(result)
          toast.success(`Đã đặt lại mật khẩu cho ${user.email}`)
        } catch (error) {
          toast.error(errorMessage(error))
          throw error
        }
      },
    })
  }

  function askResendVerification(user: AdminUserRow) {
    confirm.ask({
      title: "Gửi lại email xác thực?",
      description: `${user.email} sẽ nhận một email xác thực mới.`,
      confirmLabel: "Gửi lại",
      run: async () => {
        try {
          const message = await resendVerification.mutateAsync(user.id)
          toast.success(message)
        } catch (error) {
          toast.error(errorMessage(error))
          throw error
        }
      },
    })
  }

  function askBulk() {
    if (!bulkOp || selected.length === 0) return
    if (bulkOp !== "soft_delete" && !bulkValue) {
      toast.error("Chọn giá trị cần áp dụng")
      return
    }
    const targets = selected.map((id) => emailById.get(id) ?? id)
    const operation =
      bulkOp === "soft_delete"
        ? BULK_OP_LABELS.soft_delete
        : `${BULK_OP_LABELS[bulkOp]} → ${bulkOp === "set_role" ? labelForRole(bulkValue) : labelForStatus(bulkValue)}`
    confirm.ask({
      title: bulkOp === "soft_delete" ? "Xóa mềm người dùng?" : "Áp dụng thao tác hàng loạt?",
      description: `${operation} cho ${selected.length} người dùng.`,
      confirmLabel: bulkOp === "soft_delete" ? "Xóa mềm" : "Áp dụng",
      tone: bulkOp === "soft_delete" ? "destructive" : "default",
      body: (
        <ul className="space-y-1 text-muted-foreground">
          {targets.slice(0, 6).map((target) => (
            <li key={target} className="truncate font-mono text-xs">
              {target}
            </li>
          ))}
          {targets.length > 6 && <li className="text-xs">… và {targets.length - 6} người dùng khác</li>}
        </ul>
      ),
      run: async () => {
        try {
          const result = await bulk.mutateAsync({
            userIds: selected,
            op: bulkOp,
            value: bulkOp === "soft_delete" ? null : bulkValue,
          })
          const problems = [
            result.skipped.length > 0 ? `bỏ qua ${result.skipped.length}` : null,
            result.errors.length > 0
              ? `${result.errors.length} lỗi (${result.errors[0].message})`
              : null,
          ].filter(Boolean)
          if (problems.length > 0) {
            toast.warning(`Đã cập nhật ${result.affected} người dùng · ${problems.join(" · ")}`)
          } else {
            toast.success(`Đã cập nhật ${result.affected} người dùng`)
          }
          setSelected([])
          setBulkOp("")
          setBulkValue("")
        } catch (error) {
          toast.error(errorMessage(error))
          throw error
        }
      },
    })
  }

  function askExport() {
    confirm.ask({
      title: "Xuất CSV người dùng?",
      description: "Bộ lọc đang áp dụng sẽ được dùng cho tệp xuất.",
      confirmLabel: "Xuất CSV",
      body: (
        <div className="space-y-1 text-sm text-muted-foreground">
          <div>Tìm kiếm: {filters.search || "tất cả"}</div>
          <div>Vai trò: {filters.role === ALL ? "tất cả" : ROLE_LABELS_BY_VALUE[filters.role]}</div>
          <div>Trạng thái: {filters.status === ALL ? "tất cả" : labelForStatus(filters.status)}</div>
        </div>
      ),
      run: async () => {
        try {
          const filename = await exportCsv.mutateAsync({
            role: filters.role === ALL ? undefined : filters.role,
            status: filters.status === ALL ? undefined : filters.status,
            search: filters.search || undefined,
          })
          toast.success(`Đã xuất ${filename}`)
        } catch (error) {
          toast.error(errorMessage(error))
          throw error
        }
      },
    })
  }

  const columns: AdminColumn<AdminUserRow>[] = [
    {
      id: "email",
      header: "Email",
      sortKey: "email",
      cell: (user) => (
        <Link
          to={`/admin/users/${user.id}`}
          className="font-medium text-primary underline-offset-4 hover:underline"
        >
          {user.email}
        </Link>
      ),
    },
    {
      id: "fullName",
      header: "Tên",
      sortKey: "full_name",
      cell: (user) => user.fullName ?? <span className="text-muted-foreground">—</span>,
    },
    {
      id: "phone",
      header: "Điện thoại",
      cell: (user) =>
        user.phoneNumber ? (
          <span className="font-mono text-xs">{user.phoneNumber}</span>
        ) : (
          <span className="text-muted-foreground">—</span>
        ),
    },
    {
      id: "role",
      header: "Vai trò",
      sortKey: "role",
      cell: (user) => <StatusBadge status={user.role} label={labelForRole(user.role)} tone="info" />,
    },
    {
      id: "status",
      header: "Trạng thái",
      sortKey: "status",
      cell: (user) => <StatusBadge status={user.status} />,
    },
    {
      id: "verified",
      header: "Xác thực",
      cell: (user) => <StatusBadge status={user.isEmailVerified} label={user.isEmailVerified ? "Đã xác thực" : "Chưa xác thực"} />,
    },
    {
      id: "lastLogin",
      header: "Đăng nhập gần nhất",
      sortKey: "last_login_at",
      cell: (user) =>
        user.lastLoginAt ? (
          <span className="tabular-nums">{formatDateTime(user.lastLoginAt)}</span>
        ) : (
          <span className="text-muted-foreground">—</span>
        ),
    },
    {
      id: "createdAt",
      header: "Tạo lúc",
      sortKey: "created_at",
      cell: (user) => <span className="tabular-nums">{formatDateTime(user.createdAt)}</span>,
    },
    {
      id: "actions",
      header: "Thao tác",
      align: "right",
      cell: (user) => (
        <div className="flex items-center justify-end gap-1">
          <Button variant="ghost" size="sm" asChild>
            <Link to={`/admin/users/${user.id}`}>
              <UserCog />
              Chi tiết
            </Link>
          </Button>
          <Button
            variant="ghost"
            size="icon-sm"
            aria-label={`Đặt lại mật khẩu ${user.email}`}
            title="Đặt lại mật khẩu"
            onClick={() => askResetPassword(user)}
          >
            <KeyRound />
          </Button>
          <Button
            variant="ghost"
            size="icon-sm"
            aria-label={`Gửi lại email xác thực ${user.email}`}
            title="Gửi lại email xác thực"
            disabled={user.isEmailVerified}
            onClick={() => askResendVerification(user)}
          >
            <Mail />
          </Button>
        </div>
      ),
    },
  ]

  const state = users.data

  return (
    <WorkspacePage
      title="Người dùng"
      description={
        state ? `${state.total} người dùng khớp bộ lọc` : "Tìm kiếm, phân quyền và xử lý tài khoản người dùng"
      }
      actions={
        <Button variant="outline" size="sm" disabled={exportCsv.isPending} onClick={askExport}>
          {exportCsv.isPending ? <RotateCw className="animate-spin" /> : <Download />}
          Xuất CSV
        </Button>
      }
    >
      <form
        onSubmit={submitSearch}
        className="flex flex-wrap items-end gap-2 rounded-lg bg-card p-3 ring-1 ring-border/60 ring-inset dark:ring-0"
      >
        <div className="relative min-w-[16rem] flex-1">
          <Search className="pointer-events-none absolute top-1/2 left-2.5 size-3.5 -translate-y-1/2 text-muted-foreground" />
          <Input
            value={searchInput}
            onChange={(event) => setSearchInput(event.target.value)}
            placeholder="Tìm theo email hoặc tên"
            aria-label="Tìm theo email hoặc tên"
            className="pl-8"
          />
        </div>
        <Select value={filters.role} onValueChange={(value) => applyFilters({ role: value })}>
          <SelectTrigger className="w-[9.5rem]" aria-label="Lọc theo vai trò">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value={ALL}>Mọi vai trò</SelectItem>
            {ADMIN_ROLES.map((role) => (
              <SelectItem key={role} value={role}>
                {labelForRole(role)}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
        <Select value={filters.status} onValueChange={(value) => applyFilters({ status: value })}>
          <SelectTrigger className="w-[11rem]" aria-label="Lọc theo trạng thái">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value={ALL}>Mọi trạng thái</SelectItem>
            {ADMIN_STATUSES.map((status) => (
              <SelectItem key={status} value={status}>
                {labelForStatus(status)}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
        <Button type="submit" size="sm">
          <Search />
          Lọc
        </Button>
        {(filters.search || filters.role !== ALL || filters.status !== ALL) && (
          <Button
            type="button"
            variant="ghost"
            size="sm"
            onClick={() => {
              setSearchInput("")
              applyFilters({ search: "", role: ALL, status: ALL })
            }}
          >
            Xóa bộ lọc
          </Button>
        )}
      </form>

      {selected.length > 0 && (
        <div className="flex flex-wrap items-center gap-2 rounded-lg bg-card p-3 ring-1 ring-border/60 ring-inset dark:ring-0">
          <span className="text-sm">Đã chọn {selected.length} người dùng</span>
          <Select value={bulkOp} onValueChange={(value) => { setBulkOp(value as BulkOp); setBulkValue("") }}>
            <SelectTrigger className="w-[11rem]" aria-label="Thao tác hàng loạt">
              <SelectValue placeholder="Chọn thao tác" />
            </SelectTrigger>
            <SelectContent>
              {(Object.keys(BULK_OP_LABELS) as BulkOp[]).map((op) => (
                <SelectItem key={op} value={op}>
                  {BULK_OP_LABELS[op]}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          {bulkOp === "set_role" && (
            <Select value={bulkValue} onValueChange={setBulkValue}>
              <SelectTrigger className="w-[9.5rem]" aria-label="Vai trò áp dụng">
                <SelectValue placeholder="Vai trò" />
              </SelectTrigger>
              <SelectContent>
                {ADMIN_ROLES.map((role) => (
                  <SelectItem key={role} value={role}>
                    {labelForRole(role)}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          )}
          {bulkOp === "set_status" && (
            <Select value={bulkValue} onValueChange={setBulkValue}>
              <SelectTrigger className="w-[11rem]" aria-label="Trạng thái áp dụng">
                <SelectValue placeholder="Trạng thái" />
              </SelectTrigger>
              <SelectContent>
                {ASSIGNABLE_STATUSES.map((status) => (
                  <SelectItem key={status} value={status}>
                    {labelForStatus(status)}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          )}
          <Button size="sm" disabled={!bulkOp || bulk.isPending} onClick={askBulk}>
            Áp dụng
          </Button>
          <Button variant="ghost" size="sm" onClick={() => setSelected([])}>
            Bỏ chọn
          </Button>
        </div>
      )}

      <AdminDataTable
        columns={columns}
        rows={rows}
        rowKey={(user) => user.id}
        loading={users.isLoading || users.isFetching}
        error={users.error ? errorMessage(users.error) : null}
        onRetry={() => void users.refetch()}
        emptyLabel="Không có người dùng khớp bộ lọc."
        sort={sort}
        onSortChange={changeSort}
        selection={{
          selected,
          onToggle: (key) =>
            setSelected((previous) =>
              previous.includes(key) ? previous.filter((item) => item !== key) : [...previous, key],
            ),
          onToggleAll: (keys) =>
            setSelected((previous) => {
              const allSelected = keys.every((key) => previous.includes(key))
              return allSelected
                ? previous.filter((key) => !keys.includes(key))
                : [...new Set([...previous, ...keys])]
            }),
        }}
        pagination={{
          page,
          pageSize,
          total: state?.total ?? 0,
          totalPages: state?.totalPages ?? 1,
          onPageChange: setPage,
          onPageSizeChange: (size) => {
            setPageSize(size)
            setPage(1)
          },
        }}
      />

      {confirm.element}

      <Dialog open={temporaryPassword !== null} onOpenChange={(open) => !open && setTemporaryPassword(null)}>
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle>Mật khẩu tạm thời</DialogTitle>
            <DialogDescription>
              Chỉ hiển thị một lần. Hãy chia sẻ qua kênh an toàn và yêu cầu người dùng đổi ngay sau khi đăng nhập.
            </DialogDescription>
          </DialogHeader>
          <div className="flex items-center gap-2">
            <code className="min-w-0 flex-1 overflow-x-auto rounded-md bg-muted px-3 py-2 font-mono text-sm">
              {temporaryPassword?.temporaryPassword}
            </code>
            <Button
              variant="outline"
              size="sm"
              onClick={() => {
                if (!temporaryPassword) return
                void navigator.clipboard
                  .writeText(temporaryPassword.temporaryPassword)
                  .then(() => toast.success("Đã sao chép mật khẩu tạm thời"))
                  .catch(() => toast.error("Không sao chép được — hãy chọn và sao chép thủ công"))
              }}
            >
              <Copy />
              Sao chép
            </Button>
          </div>
          {temporaryPassword?.warning && (
            <p className="text-xs leading-5 text-muted-foreground">{temporaryPassword.warning}</p>
          )}
          <DialogFooter>
            <Button variant="outline" onClick={() => setTemporaryPassword(null)}>
              Đóng
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </WorkspacePage>
  )
}

// admin/src/features/users/UsersPage.vue
<script setup lang="ts">
import { h, onMounted, ref } from "vue"
import { RouterLink } from "vue-router"
import { Download, KeyRound, Mail, Search } from "lucide-vue-next"
import { NButton, NCard, NInput, NSelect, NSpace, type DataTableColumns } from "naive-ui"
import RemoteDataTable from "@/components/table/RemoteDataTable.vue"
import StatusTag from "@/components/common/StatusTag.vue"
import ErrorState from "@/components/common/ErrorState.vue"
import { feedback } from "@/lib/feedback"
import { fmtDateTime } from "@/lib/format"
import { labelForRole } from "@/lib/labels"
import { useRemotePage } from "@/composables/useRemotePage"
import { usersApi, type AdminUserRow, type BulkOp } from "@/lib/api/users"

const searchText = ref("")
const role = ref<string | null>(null)
const status = ref<string | null>(null)
const checked = ref<Array<string | number>>([])
const bulkOp = ref<BulkOp | null>(null)
const bulkValue = ref<string | null>(null)
const exporting = ref(false)

const page = useRemotePage<AdminUserRow>((params) => usersApi.list({ page: Number(params.page), pageSize: Number(params.pageSize), sortBy: "created_at", sortDir: "desc", search: searchText.value || undefined, role: role.value || undefined, status: status.value || undefined }))

const roleOptions = [
  { label: "Người dùng", value: "user" },
  { label: "Premium", value: "premium" },
  { label: "Quản trị viên", value: "admin" },
]
const statusOptions = [
  { label: "Đang hoạt động", value: "active" },
  { label: "Không hoạt động", value: "inactive" },
  { label: "Bị đình chỉ", value: "suspended" },
]

const columns: DataTableColumns<AdminUserRow> = [
  { type: "selection" },
  { title: "Email", key: "email", minWidth: 240, render: (row) => h(RouterLink, { to: `/users/${row.id}` }, { default: () => row.email }) },
  { title: "Tên", key: "fullName", minWidth: 180, render: (row) => row.fullName ?? "-" },
  { title: "Vai trò", key: "role", width: 120, render: (row) => h(StatusTag, { status: row.role, label: labelForRole(row.role) }) },
  { title: "Trạng thái", key: "status", width: 150, render: (row) => h(StatusTag, { status: row.status }) },
  { title: "Xác thực", key: "isEmailVerified", width: 110, render: (row) => h(StatusTag, { status: row.isEmailVerified }) },
  { title: "Đăng nhập", key: "lastLoginAt", width: 160, render: (row) => row.lastLoginAt ? fmtDateTime(row.lastLoginAt) : "-" },
  { title: "Tạo lúc", key: "createdAt", width: 160, render: (row) => fmtDateTime(row.createdAt) },
  { title: "Thao tác", key: "actions", width: 170, render: (row) => h(NSpace, { size: 4 }, { default: () => [h(NButton, { size: "small", secondary: true, onClick: () => resetPassword(row) }, { icon: () => h(KeyRound, { size: 14 }), default: () => "Đặt lại" }), h(NButton, { size: "small", secondary: true, onClick: () => resend(row) }, { icon: () => h(Mail, { size: 14 }) })] }) },
]

function loadFirstPage() { void page.load({ page: 1 }) }

function resetPassword(user: AdminUserRow) {
  feedback.dialog?.warning({
    title: "Đặt lại mật khẩu?",
    content: `Tạo mật khẩu tạm thời cho ${user.email}.`,
    positiveText: "Đặt lại",
    negativeText: "Hủy",
    onPositiveClick: async () => {
      const res = await usersApi.resetPassword(user.id)
      feedback.dialog?.success({ title: "Mật khẩu tạm thời", content: res.temporary_password, positiveText: "Đã lưu" })
    },
  })
}

async function resend(user: AdminUserRow) {
  try {
    await usersApi.resendVerification(user.id)
    feedback.message?.success(`Đã gửi lại email xác thực cho ${user.email}`)
  } catch (error) {
    feedback.message?.error(error instanceof Error ? error.message : "Gửi thất bại")
  }
}

function applyBulk() {
  if (!bulkOp.value || checked.value.length === 0) return
  if (bulkOp.value !== "soft_delete" && !bulkValue.value) {
    feedback.message?.error("Vui lòng chọn giá trị áp dụng")
    return
  }
  feedback.dialog?.warning({
    title: "Áp dụng thao tác hàng loạt?",
    content: `Cập nhật ${checked.value.length} người dùng.`,
    positiveText: "Áp dụng",
    negativeText: "Hủy",
    onPositiveClick: async () => {
      const res = await usersApi.bulk({ user_ids: checked.value.map(String), op: bulkOp.value!, value: bulkOp.value === "soft_delete" ? null : bulkValue.value })
      feedback.message?.success(`Đã cập nhật ${res.affected} người dùng`)
      checked.value = []
      bulkOp.value = null
      bulkValue.value = null
      await page.load()
    },
  })
}

async function exportCsv() {
  exporting.value = true
  try {
    const filters: Record<string, string> = {}
    if (searchText.value) filters.search = searchText.value
    if (role.value) filters.role = role.value
    if (status.value) filters.status = status.value
    await usersApi.exportCsv(filters)
    feedback.message?.success("Đã xuất CSV thành công")
  } catch (error) {
    feedback.message?.error(error instanceof Error ? error.message : "Xuất CSV thất bại")
  } finally {
    exporting.value = false
  }
}

onMounted(() => void page.load())
</script>

<template>
  <div class="page-stack">
    <div class="page-header"><div><h1 class="page-title">Người dùng</h1><p class="page-subtitle">{{ page.total.value }} người dùng</p></div><n-button secondary :loading="exporting" @click="exportCsv"><template #icon><Download :size="16" /></template>Xuất CSV</n-button></div>
    <n-card>
      <n-space align="center" wrap>
        <n-input v-model:value="searchText" clearable placeholder="Tìm email, tên..." style="width: 260px" @keyup.enter="loadFirstPage"><template #prefix><Search :size="16" /></template></n-input>
        <n-select v-model:value="role" clearable :options="roleOptions" placeholder="Vai trò" style="width: 160px" @update:value="loadFirstPage" />
        <n-select v-model:value="status" clearable :options="statusOptions" placeholder="Trạng thái" style="width: 180px" @update:value="loadFirstPage" />
        <n-button type="primary" @click="loadFirstPage">Lọc</n-button>
      </n-space>
    </n-card>
    <n-card v-if="checked.length" size="small">
      <n-space align="center" wrap>
        <span>Đã chọn {{ checked.length }} người dùng</span>
        <n-select v-model:value="bulkOp" placeholder="Thao tác" :options="[{ label: 'Đặt vai trò', value: 'set_role' }, { label: 'Đặt trạng thái', value: 'set_status' }, { label: 'Xóa mềm', value: 'soft_delete' }]" style="width: 180px" @update:value="bulkValue = null" />
        <n-select v-if="bulkOp === 'set_role'" v-model:value="bulkValue" :options="roleOptions" placeholder="Vai trò" style="width: 160px" />
        <n-select v-if="bulkOp === 'set_status'" v-model:value="bulkValue" :options="statusOptions" placeholder="Trạng thái" style="width: 180px" />
        <n-button type="primary" @click="applyBulk">Áp dụng</n-button>
        <n-button secondary @click="checked = []">Bỏ chọn</n-button>
      </n-space>
    </n-card>
    <ErrorState v-if="page.error.value" :message="page.error.value" @retry="page.load" />
    <RemoteDataTable :columns="columns" :rows="page.rows.value" :loading="page.loading.value" :page="page.params.page" :page-size="page.params.pageSize" :item-count="page.total.value" :row-key="(row) => row.id" :checked-row-keys="checked" @update-checked-row-keys="checked = $event" @page-change="page.setPage" @page-size-change="page.setPageSize" />
  </div>
</template>
