// admin/src/features/premium/PlansPage.vue
<script setup lang="ts">
import { h, onMounted, reactive, ref } from "vue"
import { Plus } from "lucide-vue-next"
import { NButton, NCard, NDataTable, NForm, NFormItem, NInput, NInputNumber, NModal, NSpace, NSwitch, type DataTableColumns } from "naive-ui"
import StatusTag from "@/components/common/StatusTag.vue"
import ErrorState from "@/components/common/ErrorState.vue"
import { feedback } from "@/lib/feedback"
import { fmtDateTime, fmtVnd } from "@/lib/format"
import { plansApi, type PlanCreate, type PlanRow } from "@/lib/api/plans"

const plans = ref<PlanRow[]>([])
const loading = ref(true)
const error = ref<string | null>(null)
const modalOpen = ref(false)
const editing = ref<PlanRow | null>(null)
const form = reactive({ code: "", name: "", description: "", priceVnd: 0, durationDays: 30, isActive: true, sortOrder: 0 })

const columns: DataTableColumns<PlanRow> = [
  { title: "Mã", key: "code", width: 140, className: "mono" },
  { title: "Tên", key: "name", minWidth: 180 },
  { title: "Giá", key: "priceVnd", render: (row) => fmtVnd(row.priceVnd) },
  { title: "Thời hạn", key: "durationDays", render: (row) => `${row.durationDays} ngày` },
  { title: "Thứ tự", key: "sortOrder" },
  { title: "Trạng thái", key: "isActive", render: (row) => h(StatusTag, { status: row.isActive, label: row.isActive ? "Đang hoạt động" : "Không hoạt động" }) },
  { title: "Ngày tạo", key: "createdAt", render: (row) => fmtDateTime(row.createdAt) },
  { title: "Thao tác", key: "actions", width: 180, render: (row) => h(NSpace, { size: 4 }, { default: () => [h(NButton, { size: "small", secondary: true, onClick: () => openEdit(row) }, { default: () => "Sửa" }), h(NButton, { size: "small", secondary: true, type: "error", disabled: row.code === "TRIAL_7D" || !row.isActive, onClick: () => deactivate(row) }, { default: () => "Ngưng" })] }) },
]

async function load() {
  loading.value = true
  error.value = null
  try {
    plans.value = (await plansApi.list()).sort((a, b) => a.sortOrder - b.sortOrder || a.name.localeCompare(b.name))
  } catch (err) { error.value = err instanceof Error ? err.message : "Không thể tải gói" } finally { loading.value = false }
}
function openCreate() { editing.value = null; Object.assign(form, { code: "", name: "", description: "", priceVnd: 0, durationDays: 30, isActive: true, sortOrder: plans.value.length + 1 }); modalOpen.value = true }
function openEdit(row: PlanRow) { editing.value = row; Object.assign(form, { code: row.code, name: row.name, description: row.description ?? "", priceVnd: row.priceVnd, durationDays: row.durationDays, isActive: row.isActive, sortOrder: row.sortOrder }); modalOpen.value = true }
async function save() {
  const body: PlanCreate = { code: form.code, name: form.name, description: form.description || null, price_vnd: form.priceVnd, duration_days: form.durationDays, is_active: form.isActive, sort_order: form.sortOrder }
  try {
    if (editing.value) await plansApi.update(editing.value.id, body)
    else await plansApi.create(body)
    feedback.message?.success("Đã lưu gói")
    modalOpen.value = false
    await load()
  } catch (err) { feedback.message?.error(err instanceof Error ? err.message : "Lưu thất bại") }
}
function deactivate(row: PlanRow) {
  feedback.dialog?.warning({ title: "Ngưng kích hoạt gói?", content: row.name, positiveText: "Ngưng", negativeText: "Hủy", onPositiveClick: async () => { await plansApi.delete(row.id); feedback.message?.success("Đã ngưng kích hoạt gói"); await load() } })
}
onMounted(() => void load())
</script>

<template>
  <div class="page-stack">
    <div class="page-header"><div><h1 class="page-title">Gói Premium</h1><p class="page-subtitle">Quản lý các gói premium</p></div><n-button type="primary" @click="openCreate"><template #icon><Plus :size="16" /></template>Tạo gói</n-button></div>
    <ErrorState v-if="error" :message="error" @retry="load" />
    <n-card><n-data-table :columns="columns" :data="plans" :loading="loading" /></n-card>
    <n-modal v-model:show="modalOpen" preset="card" :title="editing ? 'Sửa gói' : 'Tạo gói'" style="max-width: 560px">
      <n-form label-placement="top">
        <n-form-item label="Mã"><n-input v-model:value="form.code" :disabled="!!editing" /></n-form-item>
        <n-form-item label="Tên"><n-input v-model:value="form.name" /></n-form-item>
        <n-form-item label="Mô tả"><n-input v-model:value="form.description" type="textarea" /></n-form-item>
        <n-space><n-form-item label="Giá"><n-input-number v-model:value="form.priceVnd" :min="0" /></n-form-item><n-form-item label="Thời hạn"><n-input-number v-model:value="form.durationDays" :min="1" /></n-form-item><n-form-item label="Thứ tự"><n-input-number v-model:value="form.sortOrder" :min="0" /></n-form-item></n-space>
        <n-form-item label="Active"><n-switch v-model:value="form.isActive" /></n-form-item>
        <n-space justify="end"><n-button secondary @click="modalOpen = false">Hủy</n-button><n-button type="primary" @click="save">Lưu</n-button></n-space>
      </n-form>
    </n-modal>
  </div>
</template>

// admin/src/features/plans/plans-page.tsx
import { useCallback, useEffect, useState } from "react"
import { Plus, Pencil, Trash2 } from "lucide-react"
import { toast } from "sonner"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { StatusBadge } from "@/components/common/status-badge"
import { ConfirmDialog } from "@/components/common/confirm-dialog"
import { ErrorState } from "@/components/common/error-state"
import { Skeleton } from "@/components/ui/skeleton"
import { plansApi, type PlanRow } from "@/lib/api/plans"
import { fmtVnd, fmtDate } from "@/lib/format"
import { PlanDetailDrawer } from "./plan-detail-drawer"

const INTERNAL_PLANS = ["TRIAL_7D"]

export default function PlansPage() {
  const [plans, setPlans] = useState<PlanRow[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  // Drawer state
  const [drawerOpen, setDrawerOpen] = useState(false)
  const [editingPlan, setEditingPlan] = useState<PlanRow | null>(null)

  // Delete confirm
  const [deleteTarget, setDeleteTarget] = useState<PlanRow | null>(null)
  const [deleteLoading, setDeleteLoading] = useState(false)

  const fetchPlans = useCallback(async () => {
    setLoading(true)
    setError(null)
    try {
      const data = await plansApi.list()
      // Sort by sort_order asc, then name
      data.sort((a, b) => a.sortOrder - b.sortOrder || a.name.localeCompare(b.name))
      setPlans(data)
    } catch (e) {
      setError(e instanceof Error ? e.message : "Không thể tải danh sách gói")
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => { void fetchPlans() }, [fetchPlans])

  const handleCreate = () => {
    setEditingPlan(null)
    setDrawerOpen(true)
  }

  const handleEdit = (plan: PlanRow) => {
    setEditingPlan(plan)
    setDrawerOpen(true)
  }

  const handleSuccess = (plan: PlanRow) => {
    setPlans((prev) => {
      const idx = prev.findIndex((p) => p.id === plan.id)
      if (idx >= 0) {
        const next = [...prev]
        next[idx] = plan
        return next
      }
      return [...prev, plan].sort(
        (a, b) => a.sortOrder - b.sortOrder || a.name.localeCompare(b.name),
      )
    })
  }

  const handleDelete = async () => {
    if (!deleteTarget) return
    setDeleteLoading(true)
    try {
      const updated = await plansApi.delete(deleteTarget.id)
      setPlans((prev) =>
        prev.map((p) => (p.id === updated.id ? updated : p)),
      )
      toast.success("Đã ngưng kích hoạt gói")
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Thao tác thất bại")
    } finally {
      setDeleteLoading(false)
      setDeleteTarget(null)
    }
  }

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold">Gói Premium</h1>
          <p className="text-sm text-muted-foreground">
            Quản lý các gói premium
          </p>
        </div>
        <Button size="sm" onClick={handleCreate} className="gap-1.5">
          <Plus className="size-4" />
          Tạo gói mới
        </Button>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">
            Danh sách gói ({plans.length})
          </CardTitle>
        </CardHeader>
        <CardContent>
          {loading ? (
            <div className="space-y-3">
              {Array.from({ length: 4 }).map((_, i) => (
                <Skeleton key={i} className="h-12 w-full" />
              ))}
            </div>
          ) : error ? (
            <ErrorState message={error} onRetry={fetchPlans} />
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Mã</TableHead>
                  <TableHead>Tên</TableHead>
                  <TableHead>Giá (VND)</TableHead>
                  <TableHead>Thời hạn</TableHead>
                  <TableHead>Thứ tự</TableHead>
                  <TableHead>Trạng thái</TableHead>
                  <TableHead>Ngày tạo</TableHead>
                  <TableHead className="text-right">Thao tác</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {plans.map((plan) => {
                  const isInternal = INTERNAL_PLANS.includes(plan.code)
                  return (
                    <TableRow
                      key={plan.id}
                      className="cursor-pointer hover:bg-muted/50"
                      onClick={() => handleEdit(plan)}
                    >
                      <TableCell className="font-mono text-sm">
                        <div className="flex items-center gap-2">
                          {plan.code}
                          {isInternal && (
                            <Badge
                              variant="outline"
                              className="h-4 px-1.5 text-[10px] bg-amber-100 text-amber-800 border-amber-200"
                            >
                              Internal
                            </Badge>
                          )}
                        </div>
                      </TableCell>
                      <TableCell className="text-sm font-medium">
                        {plan.name}
                      </TableCell>
                      <TableCell className="text-sm">
                        {fmtVnd(plan.priceVnd)}
                      </TableCell>
                      <TableCell className="text-sm">
                        {plan.durationDays} ngày
                      </TableCell>
                      <TableCell className="text-sm">{plan.sortOrder}</TableCell>
                      <TableCell>
                        <StatusBadge
                          status={plan.isActive ? "active" : "inactive"}
                          label={plan.isActive ? "Đang hoạt động" : "Không hoạt động"}
                        />
                      </TableCell>
                      <TableCell className="text-sm text-muted-foreground">
                        {fmtDate(plan.createdAt)}
                      </TableCell>
                      <TableCell className="text-right">
                        <div
                          className="flex items-center justify-end gap-1"
                          onClick={(e) => e.stopPropagation()}
                        >
                          <Button
                            variant="ghost"
                            size="icon"
                            className="size-7"
                            onClick={() => handleEdit(plan)}
                            title="Chỉnh sửa"
                          >
                            <Pencil className="size-3.5" />
                          </Button>
                          <Button
                            variant="ghost"
                            size="icon"
                            className="size-7 text-destructive hover:text-destructive"
                            onClick={() => setDeleteTarget(plan)}
                            disabled={isInternal || !plan.isActive}
                            title={
                              isInternal
                                ? "Gói Internal không thể xoá"
                                : !plan.isActive
                                  ? "Gói đã ngưng kích hoạt"
                                  : "Ngưng kích hoạt"
                            }
                          >
                            <Trash2 className="size-3.5" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  )
                })}
                {plans.length === 0 && (
                  <TableRow>
                    <TableCell
                      colSpan={8}
                      className="py-12 text-center text-muted-foreground"
                    >
                      Chưa có gói nào
                    </TableCell>
                  </TableRow>
                )}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      {/* Drawer */}
      <PlanDetailDrawer
        open={drawerOpen}
        onOpenChange={setDrawerOpen}
        plan={editingPlan}
        onSuccess={handleSuccess}
      />

      {/* Delete confirm */}
      <ConfirmDialog
        open={!!deleteTarget}
        onOpenChange={(open) => {
          if (!open) setDeleteTarget(null)
        }}
        title="Ngưng kích hoạt gói"
        description={`Bạn có chắc muốn ngưng kích hoạt gói "${deleteTarget?.name}"? Gói sẽ được ẩn khỏi danh sách công khai nhưng vẫn tồn tại trong hệ thống.`}
        destructive
        confirmLabel={deleteLoading ? "Đang xử lý..." : "Ngưng kích hoạt"}
        onConfirm={handleDelete}
      />
    </div>
  )
}
